<?php
    
    $config_file_default    = "config.default";    
    $config_file_directory  = "../inc/";	
    $config_file_name       = "config.php";    
    $config_file_path       = $config_file_directory.$config_file_name;
    
    $application_name       = "Auto Blogspot System";
    $application_start_file = "../login.php";
    
    $license_agreement_page = "";
    
    $sql_dump               = "db_dump.sql";
?>
